From: Mauricio Gomes <mauricio@edge14.com>
"I was having trouble parsing an ICS file and I kept getting this error:

NotImplementedError: Value of type (Bignum) does not support to_ical
method! from component.rb:223:in `sequence'

I looked through the ICS file and noticed the sequence numbers were
really large, (ie, 12055194070). After looking through the RFC,
section 4.3.8 defines the valid range for "integer" as -2147483648 to
2147483647. Numbers that large in Ruby get converted to Bignum, but
the to_ical() method doesn't support it."

Signed-off-by: Jo Potts <jopotts@gmail.com>